### ISSUE TITLE
Right-click zoom to match from Conflation menu

### ISSUE THREAD

**Issue by oeon** [joshdoe/josm-conflation-plugin#1] opened 2012-05-10 16:52 UTC
A 'Right-click zoom to match from Conflation menu' could be useful. Also maybe useful: if clicking the light-blue arrows after generating matches could select the record in the Conflation menu. Not sure if this is possible, just some observations as I'm happily using this for the first time.

_UPDATE_ noticed that double-clicking in the Conflation menu centers, selects the match.
_UPDATE2_ noticed this has already been identified as 'Future work' http://wiki.openstreetmap.org/wiki/JOSM/Plugins/Conflation#Future_work

**Comment by joshdoe** [comment] 2012-05-15 11:14
Yes, it's on the TODO list, but it's not prioritized at all, so PLEASE do ask for specific enhancements, so I know what to work on next. :) You're the second confirmed user of the plugin, and actual users have significant say in the direction of the plugin, since I want it to be really useful.

**Comment by joshdoe** [comment] 2012-05-15 11:15
Actually implementing this shouldn't be hard, though I'll have to find the code bits used for finding what arrow is clicked on.

**Comment by joshdoe** [comment] 2012-06-07 02:20
FYI right-click for zoom and selection is now released in 0.1.6. I'm going to close this, since the other request for clicking on arrows should go in a separate issue.

**Closed as completed by joshdoe** 2012-06-07 02:20 UTC
Labels: enhancement
